#ifndef _C4_ERROR_H
#define _C4_ERROR_H 1

enum {
	C4_ERROR_NONE,
	C4_ERROR_INVALID_ARGUMENT,
	C4_ERROR_INVALID_OBJECT,
	C4_ERROR_INVALID_PLATFORM,
	C4_ERROR_PERMISSION_DENIED,
	C4_ERROR_NOT_IMPLEMENTED,
	C4_ERROR_ENTITY_FULL,
};

#endif
